# Generated by Django 3.2.10 on 2022-01-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True)),
                ('slug_question_1', models.SlugField()),
                ('slug_question_2', models.SlugField()),
                ('slug_question_3', models.SlugField()),
                ('slug_question_4', models.SlugField()),
                ('slug_question_5', models.SlugField()),
                ('slug_question_6', models.SlugField(blank=True)),
                ('slug_question_7', models.SlugField(blank=True)),
                ('slug_question_8', models.SlugField(blank=True)),
                ('slug_question_9', models.SlugField(blank=True)),
                ('slug_question_10', models.SlugField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
