# Generated by Django 3.2.10 on 2022-01-01 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220101_0157'),
        ('quiz_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_1', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_10',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_10', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_2', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_3', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_4', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_5', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_6',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_6', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_7',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_7', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_8',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_8', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_9',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_9', to='question.question'),
        ),
        migrations.CreateModel(
            name='FeaturedQuizGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_game_slug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz_game.quizgame')),
            ],
        ),
    ]
