# Generated by Django 3.2.10 on 2022-01-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20220101_0157'),
        ('quiz_game', '0002_auto_20220101_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_3', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_4',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_4', to='question.question'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='slug_question_5',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_5', to='question.question'),
        ),
    ]
