# Generated by Django 3.2.10 on 2022-01-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to='topic_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('wrong_answer_1', models.CharField(max_length=255)),
                ('wrong_answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('wrong_answer_3', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_source', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='question_image/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.questiontopic')),
            ],
        ),
    ]
