# Generated by Django 3.2.10 on 2022-01-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation_source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default='Allgemein', on_delete=django.db.models.deletion.PROTECT, to='question.questiontopic'),
        ),
    ]
