# Generated by Django 3.2.10 on 2021-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_questiontopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontopic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='icon',
            field=models.ImageField(default='', upload_to='topic_icon/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
