# Generated by Django 3.2.10 on 2021-12-31 20:33

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20211231_2122'),
    ]
