# Generated by Django 3.2.10 on 2021-12-31 20:34

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_questiontopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='questiontopic',
            name='topic',
            field=models.CharField(max_length=255, validators=[question.models.validate_topic_name]),
        ),
    ]
