# Generated by Django 3.2.10 on 2021-12-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20211231_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('Allgemein', 'Allgemein'), ('Natur', 'Natur'), ('Kultur', 'Kultur')], max_length=255),
        ),
    ]
